default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: innovencer_dev

test:
  <<: *default
  database: innovencer_test

production:
  <<: *default
  database: innovencer_production
  username: innovencer
  password: <%= ENV['INNOVENCER_DATABASE_PASSWORD'] %>
